version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "tvksp"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
  app:
    image: martell805/tvksp3:latest
    container_name: tvksp3
    depends_on:
      - postgres
    ports:
      - "8080:8080"
